### PR TITLE
Fix `unevaluatable_value` error reported for width cast

### LINKED ISSUE #2259: Width cast can't be used in `if_reset` statement
Width cast that the given width is imported from a package can't be used in `if_reset` statement.

Example:

```systemverilog
package Pkg {
    const W: u32 = 8;
}

module ModuleA (
    i_clk: input  clock,
    i_rst: input  reset,
    o_d  : output logic<W>,
) {
    import Pkg::*;

    var d: logic<W>;

    assign o_d = d;

    always_ff {
        if_reset {
            d = 0 as W;
        } else {
            d = d + (1 as W);
        }
    }
}
```

output
```
]8;;https://doc.veryl-lang.org/book/07_appendix/02_semantic_error.html#unevaluatable_value\unevaluatable_value (link)]8;;\

  💥 Value, which is not evaluable at elaboration, can't be used as reset
  │ value
    ╭─[:18:17]
 17 │         if_reset {
 18 │             d = 0 as W;
    ·                 ───┬──
    ·                    ╰── Error location
 19 │         } else {
    ╰────
  help: 
```

### PR DESCRIPTION
**Pull request by taichi-ishitani**
fix veryl-lang/veryl#2259

Currently, IR conversion for cast operation whose RHS is factor defined in other component is treated as error. This causes #2259.

To fix #2259, I implemented the above case.

### CODE REVIEW

File: crates/analyzer/src/conv/expression.rs [hunk 1]
```diff
@@ -708,76 +728,11 @@ impl Conv<&IdentifierFactor> for ir::Expression {
                 }
             }
         } else {
-            let x = value.expression_identifier.as_ref();
```
Comment (taichi-ishitani) [inline crates/analyzer/src/conv/expression.rs]: The same routine is needed [here](https://github.com/taichi-ishitani/veryl/blob/4aff37f82daecc5cab932cf3a12e50915a9865d7/crates/analyzer/src/conv/expression.rs#L312) too.
Therefore, split this into [`eval_factor_path`](https://github.com/taichi-ishitani/veryl/blob/4aff37f82daecc5cab932cf3a12e50915a9865d7/crates/analyzer/src/conv/utils.rs#L1207).
