### PR TITLE
[Fix] Basic Support for File Renaming and Deleting

### LINKED ISSUE #1224: [Bug] Module is marked as duplicated after moving the source file
Hello,   
I'm currently using Veryl Language Server with Veryly VSCode extension.  

It occurred that after moving a source file from a directory to another, the module and all its members (the `logic`s and `const`s) are marked as duplicated.  `Semantic Error: ModuleA is duplicated` as an instance.  

These errors are gone after executing `vscode-veryl: Restart Language Server`.

I'm working on VSCode with Veryl extension version `0.13.5`.  
My system is Windows 11 24H2.

### PR DESCRIPTION
**Pull request by Hamster5295**
Closes #1224

### CODE REVIEW

File: crates/languageserver/src/server.rs [hunk 1]
```diff
@@ -31,6 +32,16 @@ pub enum MsgToServer {
         version: i32,
     },
     DidChangeConfiguration(ServerConfigItem),
+    WillRenameFile {
+        old_url: String,
```
Comment (dalance) [inline crates/languageserver/src/server.rs:36]: I can understand the reason that type of url is `String` in newly added variants, it is came from `lsp_types::FileRename`.
But `Url` may be more appropriate, because it is more consistent with the name of field, and finally it is converted to `Url` in `did_rename_files`.

**Comment by dalance** [comment]
Thank you for your contribution!
I think logic of the code has no problem, and commented a point about type definition.

File: crates/languageserver/src/server.rs (hunk 1 above)
Comment (Hamster5295) [reply crates/languageserver/src/server.rs]: Get it!

**Comment by dalance** [comment]
Looks good!
I'll merge this PR.
